config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'recipes/generate'
  get 'recipes/search'
  get 'recipes/suggest', constraints: { format: 'json' }
  get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  post 'sessions/create'# , constraints: { format: 'json' }
  delete 'sessions/destroy'

  get 'users/:username/search_histories', to: 'users#search_histories',
                                          as: 'user_search_histories',
                                          constraints: { username: /[%\w.\-]+?/, format: 'html' }
  resources :users, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates_presence_of :name, :description
  validates :time, presence: true, numericality: { only_integer: true, less_than_or_equal_to: ActiveSupport::Duration::SECONDS_PER_WEEK / ActiveSupport::Duration::SECONDS_PER_MINUTE }
  validates :difficulty, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 5 }
  validates_length_of :name, maximum: 255, allow_blank: false
  validates_length_of :description, maximum: 1000, allow_blank: false

  default_scope { order(:id) }
  scope :name_liked, ->(keyword) { where('name LIKE?', "%#{keyword}%") }

  paginates_per 10
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  default_scope { order(:id) }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.username = username.downcase }
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :search_histories, dependent: :destroy

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  after_action :save_search_history, only: :search, if: -> { signed_in? }

  def generate
    id = Recipe.select(:id).find_by(generate_params)
    if id.nil?
      redirect_back(fallback_location: root_path)
    else
      redirect_to recipe_path(id: id)
    end
  end

  def suggest
    @recipes = Recipe.name_liked(params[:name]).select(:id, :name)
    render layout: false
  end

  def search
    @recipes = Recipe.name_liked(params[:name]).page(params[:page])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  private

  def generate_params
    params.require(:recipe).permit(:name)
  end

  def save_search_history
    current_user.search_histories.create(keyword: params[:name])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: session_params[:username].downcase)
    if user&.authenticate(session_params[:password])
      sign_in user
      session_params[:remember_me] == '1' ? remember(user) : forget(user)
      render layout: false
    else
      flash.now[:error] = 'Failed to sign in! Username or password is incorrect.'
      render json: flash, status: :bad_request
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:username, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render layout: false
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      render template: 'sessions/create', layout: false
    else
      render template: 'shared/_error_messages', layout: false
    end
  end

  def search_histories
    user = User.find_by!(username: params[:username].downcase)
    @search_histories = user.search_histories
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Signs in the given user.
  def sign_in(user)
    session[:user_id] = user.id
  end

  # Remembers an user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current signed-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        sign_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is signed in, false otherwise.
  def signed_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Signs out the current user.
  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-red-500 p-6">
  <%= link_to root_path, class: 'flex items-center flex-shrink-0 text-white mr-6' do %>
    <span class="font-semibold text-xl tracking-tight">Recipes Searcher</span>
  <% end %>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-red-200 border-red-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-red-200 hover:text-white mr-4">
        Docs
      </a>
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-red-200 hover:text-white mr-4">
        Examples
      </a>
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-red-200 hover:text-white">
        Blog
      </a>
    </div>
    <div>
      <div data-controller="session" class="flex space-x-4">
        <% if signed_in? %>
        <%= render template: '/sessions/create' %>
        <% else %>
        <div data-controller="user" data-action="ajax:success->user#successHandler ajax:error->user#errorHandler">
          <%= link_to "Sign Up", new_user_path, remote: true, class: 'inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-red-500 hover:bg-white mt-4 lg:mt-0' %>
          <div data-target="user.modal">
          </div>
        </div>
        <button data-action="click->session#showModal" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-red-500 hover:bg-white mt-4 lg:mt-0">Sign In</button>
        <%= render template: '/sessions/new' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-red-500">
    <%= render partial: 'header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex flex-col justify-center h-screen w-screen pb-64">
  <div>
    <h1 class="text-5xl text-center text-white mb-10">Recipes Searcher</h1>
  </div>
  <div data-controller="search" data-search-url="<%= recipes_search_path() %>" class="container mx-auto rounded px-8 pb-40">
    <div class="bg-white flex items-center rounded-full shadow-xl">
      <input data-action="input->search#suggest change->search#search"
             data-target="search.name"
             aria-expanded="false"
             class="rounded-l-full w-full py-4 px-6 text-gray-700 leading-tight focus:outline-none" id="search" type="text" placeholder="Search">
      <%= link_to "Suggest", recipes_suggest_path + "?name=", data: { target: "search.suggest", action: "ajax:success->search#successHandler ajax:error->search#errorHandler" }, remote: true, style: "display: none;" %>
      <div class="p-4">
      </div>
    </div>
    <div class="mt-1 rounded-md shadow-lg">
      <div class="rounded-md bg-white shadow-xs">
        <div data-target="search.recipes" class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu" hidden>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_paginate.html.erb
<div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 rounded-b-lg sm:px-6">
  <div class="flex-1 flex justify-between sm:hidden">
    <a href="#" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
      Previous
    </a>
    <a href="#" class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
      Next
    </a>
  </div>
  <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
    <div>
      <p class="text-sm leading-5 text-gray-700">
        Showing
        <span class="font-medium">1</span>
        to
        <span class="font-medium">
          <% if @recipes.total_count > 10 %>
          <%= 10 %>
          <% else %>
          <% @recipes.total_count %>
          <% end %>
        </span>
        of
        <span class="font-medium"><%= @recipes.total_count %></span>
        results
      </p>
    </div>
    <div>
      <%= paginate @recipes %>
    </div>
  </div>
</div>

app/views/recipes/search.html.erb
<div class="w-full h-full">
  <div class="container mx-auto divide-y pt-4 pb-4 px-64">
    <div class="bg-gray-100 px-4 py-5 border-b rounded-t-lg border-gray-200 sm:px-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        Recipes Search Result
      </h3>
    </div>
    <div class="flex flex-col bg-white divide-y divide-gray shadow-xl">
      <% @recipes.each do |recipe| %>
      <div class="grid grid-cols-2 p-6 gap-8">
        <div class="">
          <div class="text-sm font-medium text-gray-500">Recipe Name</div>
          <div class="">
            <div class="">
              <%= link_to recipe.name, url_for(recipe) %>
            </div>
          </div>
        </div>
        <div class="">
          <div class="text-sm font-medium text-gray-500">Difficulty</div>
          <div class="">
            <% recipe.difficulty.times do %>
            ★
            <% end %>
          </div>
        </div>
        <div class="">
          <div class="text-sm font-medium text-gray-500">Time</div>
          <div class=""><%= recipe.time %> minutes</div>
        </div>
        <div class="">
          <div class="text-sm font-medium text-gray-500">Description</div>
          <p class="truncate"><%= recipe.description %></p>
        </div>
      </div>
      <% end %>
    </div>
    <%= render 'paginate' %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="w-screen h-screen pt-16">
  <div class="bg-white shadow overflow-hidden sm:rounded-lg container m-auto w-2/3">
    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        <%= @recipe.name %>
      </h3>
      <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
        Personal details and application.
      </p>
    </div>
    <div>
      <dl>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            Difficulty
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
            <% @recipe.difficulty.times do %>
            ★
            <% end %>
          </dd>
        </div>
        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            Time
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
            <%= @recipe.time %> minutes
          </dd>
        </div>
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            Description
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
            <%= @recipe.description %>
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>

app/views/recipes/suggest.html.erb
<% @recipes.each do |recipe| %>
<%= link_to recipe.name, recipe_path(recipe.id), class: 'block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900', role: 'menuitem' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<strong class="font-bold">Holy smokes!</strong>
<ul class="list-disc">
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<span data-target="user.alertMessage" class="block sm:inline"></span>
<span data-action="click->user#hideAlert" class="absolute top-0 bottom-0 right-0 px-4 py-3">
  <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
</span>
<% end %>

app/views/users/new.html.erb
<div class="fixed z-10 inset-0 overflow-y-auto">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 transition-opacity">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>
    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>&#8203;
    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
      <%= form_with url: users_path, scope: :user, data: { action:"ajax:success->user#createSuccess ajax:error->user#createFail" }, class: "bg-white shadow-md rounded px-8 pt-6 pb-8" do |f| %>
      <div data-target="user.alert" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert" hidden>
        <strong class="font-bold">Holy smokes!</strong>
        <span data-target="user.alertMessage" class="block sm:inline"></span>
        <span data-action="click->user#hideAlert" class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
        </span>
      </div>
      <div class="mb-4">
        <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :name, placeholder: "Name", data: { target: 'user.name' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="mb-0">
        <%= f.label :username, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :username, placeholder: "Username", data: { target: 'user.username' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="mb-0">
        <%= f.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.email_field :email, placeholder: "Email", data: { target: 'user.email' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="mb-0">
        <%= f.label :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.password_field :password, data: { target: 'user.password' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "******************" %>
      </div>
      <div class="mb-6">
        <%= f.label :password_confirmation, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.password_field :password_confirmation, data: { target: 'user.passwordConfirmation' }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "******************" %>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit "Submit", class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        <button data-action="click->user#hideModal" class="bg-gray-400 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button">
          Cancel
        </button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/search_histories.html.erb
<div class="w-full h-full">
  <div class="container mx-auto divide-y pt-4 pb-4 px-64">
    <div class="bg-gray-100 px-4 py-5 border-b rounded-t-lg border-gray-200 sm:px-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">Recipes Search Histories</h3>
    </div>
    <div class="flex flex-col bg-white divide-y divide-gray shadow-xl">
      <% @search_histories.each do |search| %>
      <div class="grid grid-cols-2 p-6 gap-8">
        <div class="">
          <div class="text-sm font-medium text-gray-500">Keyword</div>
          <div class="">
            <div class="">
              <%= link_to search.keyword, recipes_search_path(name: search.keyword) %>
            </div>
          </div>
        </div>
        <div class="">
          <div class="text-sm font-medium text-gray-500">Search At</div>
          <div class=""><%= search.created_at.strftime("%F %T") %></div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>